config/routes.rb
CommercialApp::Application.routes.draw do

  root :to => "pages#home"
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/business_signup', :to => 'users#business_new'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/vote',    :to => 'votes#vote'
  match '/choose_winner', :to => 'commercials#choose_winner'
  match '/business_users', :to => 'users#business_index'
  match '/embed_help', :to => 'posts#embed_help'
  
  resources :users
 	resources :commercials
 	resources :posts, :except => [:index]
  resources :sessions, :only => [:new, :create, :destroy]
 

end

app/views/pages/_intro_text.html.erb
		<h1>You don't have to be annyoing to advertise on the Internet. You don't have to bombard regular denizens of the World Wide Web with annoying flashing banners about credit scores or finding their old classmates, while they are simply looking up how to cook spaghetti. In fact, you don't have to come to them at all. You can have them come to you and have fun, providing potential for your ads to go viral.</h1>
		<h4>Let us introduce you to the stars of Commercialize! First and foremost, there's YOU. You are a great business, whether startup or Fortune 500, seeking to connect to the world in new ways during the Internet Age. And there are Posters, namely, ordinary citizens who can join Commercialize at any time and post videos to the site.</h4>
		<h4>Commercialize is the perfect venue for you to host a 'Create your own commercial' contest for your fans. You create the contest instructions, and Posters (ordinary citizens, remember?) will begin to post their own videos depicting commercial advertisements for your company. Your contest instructions can be general, such as "Make an original and creative commercial about my company." Or, you can be specific, such as by providing an actual transcript of the commercial, and the Posters must create a video commercial that (mostly) follows the transcript.</h4>
		<h4>These commercials are available for the whole world to see. Even if a visitor doesn't post, he or she can vote on the commercials, and view the most popular ones.</h4>
		<h4>When the contest is over, you can select the winner (based on whatever criteria you prefer, it doesn't have to be based on visitors' votes) and the winner will receive whatever prize is indicated in your contest rules. Remember, the better the prize, the more video posts you'll probably get!</h4>
		<p>You also have complete control over the videos posted to your contest, and you can delete any that you deem inappropriate.</p>
		<p>Since we've just launched, pricing is extremely low at just $99 per month that the contest is displayed at our site.</p>
		<h4 class="red_color">But until May 31, we are offering the first month free. Take advantage of this offer you will never see again!</h4>
		<h1>It's so easy to get started. Connect with people all over the world now through your commercial contest. Let the fun begin!</h1>

app/views/pages/about.html.erb
<div class="centerize">
<h1>Commercialize is the right way to advertise on the World Wide Web today.</h1>
<h4> Instead of banner ads and flash videos that attempt to grab web surfers' attention in irrelevant and ineffective ways, Commercialize provides a venue for businesses of all sizes to host advertisements that Internet users actually want to see and get involved in. And it's really easy to use.
</h4>
<h4>Any business can launch a "Create your own commercial" contest, in which anyone can participate by posting his or her own homemade video that follows the particular rules for that contest. All the videos are open for anyone to view, and viewers can express their opinion by voting "Thumbs up" or "Thumbs down" for any video. When the contest is over, the company selects the winning video (based on its own criteria), and the video's submitter wins the prize as described in the contest's rules!</h4>
<h3>Sign up now to post your own videos and to vote on all the others!</h3>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %><br />	
<p>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</p>
<h2><strong>For businesses:</strong></h2>
<%= render 'pages/intro_text' %>
<%= link_to "Businesses start here!", business_signup_path, :class => "b_signup_button round" %>
</div>

app/views/pages/contact.html.erb
<h1>Contact us!</h1>
<p>You can reach us at: admin@commercialize.com</p>

app/views/pages/home.html.erb
			
	<h1>Welcome to Commercialize, the ultimate hub for 'Make your own commercial' contests! Create your own commercials for different companies and win major prizes AND watch your commercials go viral!</h1>
	<div id="poster portal">
		<h3>There have probably been times when you have watched a commercial and thought to yourself (or yelled aloud), "I could create a much better commercial than that!" Well, now you finally can. Not only that, but your commercial can be seen by the world, and you can win contests and major prizes! Sign up
		here to get started:
		<p></p>
		<div class="centerize"><%= link_to "Learn more", about_path %></div>
		</h3>
		<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
	</div>
	<p>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~</p>
	<div id="business portal">
		<h3>Are you a business who wants to take advantage of a unique and effective form of
		advertising? You can post your commercial contests right here! Get started
		today! It's really easy!<br /><br />
		<div class="centerize"><%= link_to "Learn more", about_path %></div>
		</h3>
		<%= link_to "Businesses start here!", business_signup_path,
																	 :class => "b_signup_button round" %>
	</div>


		 

app/views/pages/introduction.html.erb
<h1>Welcome, <%= "#{current_user.name}" %>. Now, for some introductions.</h1>
<%= render 'intro_text' %>

		 
<%= link_to "BEGIN", new_commercial_path, :class => "b_signup_button round" %>

app/views/pages/poster_home.html.erb
<h1>Welcome, <%= "#{current_user.name}" %>.</h1>
<h3>At Commercialize, you don't have to sit and watch commercials. You can make your own!</h3>
<p>To start, you want to view the various commercial contests out there. To do so, click the "Commercials" link at the top of the page.</p> either click