config/routes.rb
CommercialApp::Application.routes.draw do

  root :to => "pages#home"
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/business_signup', :to => 'users#business_new'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/vote',    :to => 'votes#vote'
  match '/choose_winner', :to => 'commercials#choose_winner'
  match '/business_users', :to => 'users#business_index'
  match '/embed_help', :to => 'posts#embed_help'
  
  resources :users
 	resources :commercials
 	resources :posts, :except => [:index]
  resources :sessions, :only => [:new, :create, :destroy]
 

end

app/models/commercial.rb
# == Schema Information
# Schema version: 20110117021313
#
# Table name: commercials
#
#  id         :integer         not null, primary key
#  transcript :text
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  closed     :boolean
#  title      :string(255)
#

class Commercial < ActiveRecord::Base
	#attr_accessible :title, :transcript
	
	has_many :posts
	belongs_to :user

  validates :transcript, :presence => true
  validates :user_id,    :presence => true
  validates :title,    :presence => true
  
  default_scope :order => 'commercials.created_at DESC'
  scope :limit_5, limit(5)
  


end

app/controllers/commercials_controller.rb
class CommercialsController < ApplicationController
	before_filter :authenticate, :except => [:index, :show]
	before_filter :business_filter, :except => [:index, :show]
	before_filter :correct_user, :only => [:edit, :update, :destroy]
	before_filter :winner_auth, :only => [:choose_winner]
	
  def index
  	search = params[:search]
  	if search
  		@commercials = Commercial.where("title LIKE :term OR transcript LIKE :term", :term => "%#{search}%")
  		User.businesses.where("name LIKE :term", :term => "%#{search}%").each do |user|
  			user.commercials.each do |commercial|
	  			@commercials << commercial unless @commercials.include?(commercial)
  			end
  		end
  		@search_message = "Sorry, no matches found." if @commercials.empty?
  	else
  		@commercials = Commercial.all
  	end  	
  	@title = "All the commercials!"
  end

  def show
  	@commercial = Commercial.find(params[:id])
  	@show = true # lets commercial partial in view know it's coming from show action
  	@posts = @commercial.posts.recent
  	@posts = @commercial.posts.popular if params[:view] == "popular"
  	@title = "Commercial contest from #{@commercial.user.name}"
  end

  def new
  	@title = "Post a new commercial transcipt!"
  	@commercial = Commercial.new
  end

  def create
  	@commercial = current_user.commercials.build(params[:commercial])
  	if @commercial.save
  		flash[:success] = "Commercial created!"
  		redirect_to user_path(current_user)
  	else
  		flash[:error] = "Commercial not created."
  		render 'new'
  	end
  end

  def edit
    @commercial = Commercial.find(params[:id])
  	@title = "Edit commercial transcript"
  end

  def update
  	@commercial = Commercial.find(params[:id])
  	if @commercial.update_attributes(params[:commercial])
  		flash[:success] = "Commercial updated!"
  		redirect_to user_path(current_user)
  	else
  		flash[:error] = "Commercial not created."
  		render 'edit'
  	end
  end

  def destroy
  	Commercial.find(params[:id]).destroy
		flash[:success] = "Commercial destroyed."
		redirect_to user_path(current_user)
  end
  
  def choose_winner
  	logger.debug " howdy post #{@post.title} howdy commercial #{@commercial.transcript}"
  	@post.toggle!(:winner)
  	@commercial.toggle!(:closed)
  	redirect_to commercial_path(@commercial)
  end
  
  private
  	
  	def correct_user
  		@user = Commercial.find(params[:id]).user
  		redirect_to(root_path) unless current_user?(@user)
		end
		
		def winner_auth
	  	@post = Post.find(params[:post])
	  	@commercial = @post.commercial
	  	redirect_to(root_path) unless !@commercial.closed? && current_user?(@commercial.user)
		end
end

app/helpers/commercials_helper.rb
module CommercialsHelper
end

app/views/commercials/_commercial.html.erb
<tr>
	<h4 class="commercial_business"><%= gravatar_for commercial.user, :size => 40 %>&nbsp;<%= link_to "#{commercial.user.name}", user_path(commercial.user) %></h4>
	<td class="commerical center">
		<% if @show %><div align="center" class="medium_font">
			<%= link_to "Sort by date", commercial_path(commercial, :view => "recent") %><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
			<%= link_to "Sort by votes", commercial_path(commercial, :view => "popular") %><br />
			</div>
		<% end %>

		<h5 class="commercial_title"><%= "#{commercial.title}" %></h5>
		<h6>Contest details:</h6>
		<p class="transcript"><%= commercial.transcript %></p>
		<span class="timestamp">
			Launched <%= time_ago_in_words(commercial.created_at) %> ago.
		</span>
		<% if current_user == commercial.user %>	
			<%= link_to "Edit", edit_commercial_path(commercial) %>
			<%= link_to "Delete", commercial, :method => :delete, :confirm => "Are you sure?" %>
		<% end %>
		<% if signed_in? && !(current_user.business_user?) && @show %>
			<%= link_to "Post a video!", new_post_path(:commercial_id => commercial.id), :class => "post_button round" %>
		<% end %>
		<br />
		<% if @show %>
			<%= render @posts %>
		<% else %>
			<%= link_to "Go to contest!", commercial_path(commercial), :class => "contest_button round" %>
			 <div class="centerize"><%= pluralize(commercial.posts.count, "post") %></div>
		<% end %>		
			<br /><br />
	</td>
</tr>

app/views/commercials/_commercial_form.html.erb
<%= form_for @commercial do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	<strong>Detailed contest instructions:</strong>
	<div class="field">
		<%= f.text_area :transcript %>
	</div>
	<div class="actions">
		<%= f.submit "Submit" %>
	</div>
<% end %>

app/views/commercials/edit.html.erb
<h1>Edit the contest information below:</h1>
<%= render 'commercial_form' %>

app/views/commercials/index.html.erb
<h1>Listing of active commercial contests:</h1>
<span class="center medium_font"><%= link_to "See all", commercials_path %></span>
<ul class="commercials">
	<%= render @commercials %>
</ul>

app/views/commercials/new.html.erb
<h1>Enter your commercial contest information below:</h1>
<%= render 'commercial_form' %>

app/views/commercials/show.html.erb
<h1>Commercial contest from <%= "#{@commercial.user.name}" %></h1>
<div>
	<%= render @commercial %>
</div>