config/routes.rb
CommercialApp::Application.routes.draw do

  root :to => "pages#home"
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/business_signup', :to => 'users#business_new'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/vote',    :to => 'votes#vote'
  match '/choose_winner', :to => 'commercials#choose_winner'
  match '/business_users', :to => 'users#business_index'
  match '/embed_help', :to => 'posts#embed_help'
  
  resources :users
 	resources :commercials
 	resources :posts, :except => [:index]
  resources :sessions, :only => [:new, :create, :destroy]
 

end

app/models/post.rb
# == Schema Information
# Schema version: 20110117163458
#
# Table name: posts
#
#  id            :integer         not null, primary key
#  title         :string(255)
#  user_id       :integer
#  created_at    :datetime
#  updated_at    :datetime
#  commercial_id :integer
#  vote_total    :integer
#  winner        :boolean
#  video_id      :string(255)
#

class Post < ActiveRecord::Base
	attr_accessor :embed_text
	#attr_accessible :title, :embed_text
	has_many   :votes, :dependent => :destroy
	belongs_to :user
	belongs_to :commercial

	validates :title,      :presence => true
	validates :embed_text, :presence => true, :on => :create
	
	before_create :extract_video_id
	before_create :initialize_vote_total
	
	scope :recent,  order('created_at DESC')
	scope :popular, order('vote_total DESC')
	scope :limit_3, limit(3)
	
	def extract_video_id
		self.video_id = /youtube.com\/v\/([\w-]*)\?/.match(embed_text)[1]	
	end
	
	def video_display
		return "<object width=\"480\" height=\"385\"><param name=\"movie\" value=\"http://www.youtube.com/v/" + video_id + "?fs=1&amp;hl=en_US&amp;rel=0\"></param><param name=\"allowFullScreen\" value=\"true\"></param><param name=\"allowscriptaccess\" value=\"always\"></param><embed src=\"http://www.youtube.com/v/" + video_id + "?fs=1&amp;hl=en_US&amp;rel=0\" type=\"application/x-shockwave-flash\" allowscriptaccess=\"always\" allowfullscreen=\"true\" width=\"480\" height=\"385\"></embed></object>"
	end
	
	def thumbnail	
  	thumbnail_url = "http://img.youtube.com/vi/" + video_id + "/1.jpg"
	end
	
	def initialize_vote_total
		self.vote_total = 0
	end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate, :except => [:show]
	before_filter :non_business_filter, :except => [:edit, :update, :destroy, :show]
	before_filter :correct_user, :only => [:edit, :update, :destroy]
	
	def new
		@title = "Post video"
		@post = Post.new
		@commercial = Commercial.find(params[:commercial_id])
	end

	def create
		@post = current_user.posts.build(params[:post])
		@commercial = @post.commercial
  	if @post.save
  		flash[:success] = "Video posted!"
  		redirect_to commercial_path(@post.commercial)
  	else
  		flash[:error] = "Post not created."
  		render 'new'
  	end
	end
	
	def show
		@post = Post.find(params[:id])
		@title = @post.title
		render 'show'
	end
	
	def edit
		render 'edit'
	end
	
	def update
		if @post.update_attributes(params[:post])
			flash[:success] = "Post successfully edited!"
			redirect_to commercial_path(@post.commercial)
		else
			flash[:error] = "Post has not changed."
			render 'edit'
		end
	end
	
	def destroy
		@post.destroy
		flash[:success] = "Post destroyed."
		redirect_to commercial_path(@commercial)
	end
	
	private
  	
  	def correct_user
  		@post = Post.find(params[:id])
  		@commercial = @post.commercial
  		@user = Post.find(params[:id]).user
  		#logger.debug "howdy howdy howdy #{@post} #{@commercial} #{commercial.user}"
  		redirect_to(root_path) unless current_user?(@user) || current_user?(@commercial.user)
		end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<div class="centerize">
<% if post.winner? %>
	<span id="winner">This is the winning post!</span><br />
<% end %>
<span><%= gravatar_for post.user, :size => 40 %>From&nbsp;<%= "#{post.user.name}" %>:&nbsp;</span>
<span><%= "#{post.title}" %></span><br />
<%= link_to image_tag("#{post.thumbnail}"), post_path(post), :class => "centerize" %><br />
<span class="timestamp">
	Posted <%= time_ago_in_words(post.created_at) %> ago.
</span><br />
<span>Current vote score: <div id="<%= post.title %>" class="medium_font"><%= "#{post.vote_total}" %></div></span><br />


<% if (current_user == post.user) || (current_user == post.commercial.user) %>	
	<%= link_to "Edit", edit_post_path(post) %>
	<%= link_to "Delete", post, :method => :delete, :confirm => "Are you sure?" %>
<% end %>
<% if current_user == post.commercial.user && !post.commercial.closed? %>
	<%= link_to "Select as winner", choose_winner_path(:post => post.id), 
																										 :confirm => "Are you sure that you want to select this post as the winner?" %>
<% end %>
<br /><br />
</div>

app/views/posts/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <p class="center">First, you must <%= link_to "upload your video to YouTube", "http://upload.youtube.com/my_videos_upload", :target => "_blank" %>. Then, fill out the information requested below.</p>
  <div class="field">
    <%= f.label :title %>&nbsp;&nbsp;(Create a title for your video.)<br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :embed_code %>&nbsp;&nbsp;&nbsp;<%= link_to "What on earth is an embed code?!", embed_help_path, :target => "_blank" %><br />
    <%= f.text_area :embed_text %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
  <div>
  	<%= f.hidden_field :commercial_id, :value => @commercial.id %>
  </div>
  <p><strong>Contest:</strong> <%= "#{@commercial.title}" %></p>
  <p><strong>Details:</strong> <%= "#{@commercial.transcript}" %></p>
<% end %>

app/views/posts/edit.html.erb
<%= render 'post_form' %>

app/views/posts/embed_help.html.erb
<div class="centerize">
<p>Every YouTube video has its own embed code. To find it, click on the "Embed" button below the video. See picture below.</p>
<%= image_tag("/images/embed_first.png", :alt => "Shot of Youtube", :size => "600x500", :title => "Picture 1") %><br />
<p>Clicking on embed will reveal the embed code. Copy it by right clicking it and selecting 'Copy' or by pressing Ctrl-C. See picture below.</p>
<%= image_tag("/images/embed_second.png", :alt => "Shot of Youtube", :size => "600x500", :title => "Picture 1") %><br />
<p>You can then close this tab or window and paste the embed code into the Embed Code textbox by right clicking and selecting Paste or by pressing Ctrl-V. It's as simple as that!</p>
</div>

app/views/posts/new.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :embed_text %><br />
    <%= f.text_area :embed_text %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
  <div>
  	<%= f.hidden_field :commercial_id, :value => @commercial.id %>
  </div>
  <p>Transcript: <%= "#{@commercial.transcript}" %></p>
<% end %>

app/views/posts/show.html.erb
<% if @post.winner? %>
	<span id="winner">This is the winning post!</span><br />
<% end %>
<span><%= gravatar_for @post.user, :size => 40 %>From&nbsp;<%= "#{@post.user.name}" %>:&nbsp;</span>
<span><%= "#{@post.title}" %></span><br />
<div><%= sanitize @post.video_display, :tags => %w(embed object param) %></div>
		<span class="timestamp">
			Posted <%= time_ago_in_words(@post.created_at) %> ago.
		</span><br />
<span>Current vote score: <div id="<%= @post.title %>" class="medium_font"><%= "#{@post.vote_total}" %></div></span><br />
<% if signed_in? && !current_user.business_user? %>	
	<%= link_to image_tag("thumbs_up.gif", :alt => "Vote thumbs up!", :class => "thumb"), vote_path(:value => 1, :post => @post.id), :class => "thumbs_up_button",
			:remote => true %>
	<%= link_to image_tag("thumbs_down.gif", :alt => "Vote thumbs down!", :class => "thumb"), vote_path(:value => -1,
											  :post => @post.id), :class => "thumbs_down_button", :remote => true %>
	<% @vote = Vote.find_by_user_id_and_post_id(current_user.id, @post.id) %>
	<div id="vote<%= @post.id %>">
	<% if @vote %>
		<p>You voted 
				<% if @vote.value == 1 %><%= image_tag("thumbs_up.gif", :alt => "Thumbs up!") %>  <% end %>
				<% if @vote.value == -1 %><%= image_tag("thumbs_down.gif", :alt => "Thumbs down!") %>  <% end %>
		</p>
	<% else %>
		<div id="no_vote"> You have not yet voted! </div>
	<% end %>
	</div>
<% end %>
<% if (current_user == @post.user) || (current_user == @post.commercial.user) %>	
	<%= link_to "Edit", edit_post_path(@post) %>
	<%= link_to "Delete", @post, :method => :delete, :confirm => "Are you sure?" %>
<% end %>
<% if current_user == @post.commercial.user && !@post.commercial.closed? %>
	<%= link_to "Select as winner", choose_winner_path(:post => @post.id), 
																										 :confirm => "Are you sure that you want to select this post as the winner?" %>
<% end %>
<%= link_to "Go to contest!", commercial_path(@post.commercial), :class => "contest_button round" %>