config/routes.rb
CommercialApp::Application.routes.draw do

  root :to => "pages#home"
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/business_signup', :to => 'users#business_new'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/vote',    :to => 'votes#vote'
  match '/choose_winner', :to => 'commercials#choose_winner'
  match '/business_users', :to => 'users#business_index'
  match '/embed_help', :to => 'posts#embed_help'
  
  resources :users
 	resources :commercials
 	resources :posts, :except => [:index]
  resources :sessions, :only => [:new, :create, :destroy]
 

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Businesses", business_users_path %></li>
      <li><%= link_to "Contact us", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "How it works", about_path %></li>
      <li><%= link_to "Contests", commercials_path %></li>
      <% if signed_in? %>
      <li><%= link_to "Profile", current_user %></li>
      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
      <% end %>
      <% if signed_in? %>
      <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <li><%= link_to "Sign up", signup_path %></li>
      <li><%= link_to "Business sign up", business_signup_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_popular.html.erb
<div class="main round">	
	<strong>Recently posted contests:</strong><br />
	<% recent_commercials.each do |commercial| %>
	
		<%= gravatar_for commercial.user %>	 
		
		<%= link_to "#{commercial.title}", commercial_path(commercial) %><br />
		
	
	<% end %>
</div>
<div class="bottombar round">
	<strong>Highest voted commercials:</strong><br />
			<% popular_posts.each do |post| %>
 
				<%= link_to image_tag("#{post.thumbnail}"), post_path(post) %><br />
				<%= link_to "#{post.title}", post_path(post) %><br />
			
			<% end %>
			
</div>

app/views/layouts/_search.html.erb
<%= form_tag commercials_path, :class => 'search', :method => 'get' do %>
	
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search contests", :name => nil %>&nbsp;&nbsp;
	
<% end %>
<% if @search_message %>
	<h3><%= "#{@search_message}" %></h3>
<% end %>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>


  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= render 'layouts/stylesheets' %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/header' %>
    <section class="round">
       <%= render 'layouts/search' %>
      <% flash.each do |key, value| %>
        <div class="flash <%=key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </section>
<%= render 'layouts/popular' %>
    <%= render 'layouts/footer' %>

    <%= debug(params) if Rails.env.development? && false %>
    
  </div>
 		
</body>
</html>